# Generated by Django 5.2.6 on 2025-10-14 08:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiapp", "0007_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
