# Generated by Django 5.2.6 on 2025-10-14 08:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiapp", "0008_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
